language: swift
osx_image: xcode12.2
xcode_project: TriangleApp.xcodeproj
xcode_scheme: TriangleApp
xcode_destination: "platform:iOS Simulator,id:E84D7F10-4324-4DFD-9B14-D350A9CEC627,OS:14.2,name:iPhone 11"
